config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'positions#index'
  
  # Positions related routes
  resources :positions

  # Applicant related routes
  get '/applicants/new/:id', to: 'applicants#new'
  post '/applicants/create/:id', to: 'applicants#create'
  get '/applicants/:id', to: 'applicants#show', as: 'applicant'
  get '/applicants/:id/edit', to: 'applicants#edit'
  patch '/applicants/:id', to: 'applicants#update'
  get '/applicants', to: 'applicants#index'
  delete '/applicants/:id', to: 'applicants#destroy'
  get '/positions/:id/applicants', to: 'applicants#positions'
  get '/applicants/:id/recruiters', to: 'applicants#recruiters'
  post '/applicants/update_recruiter/:id', to: 'applicants#update_recruiter'
  post '/applicant_invite/:id', to: 'applicants#applicant_invite'

  # Positions related routes
  resources :recruiters

  # Google calendar routes
  get '/redirect', to: 'calendar_api#redirect', as: 'redirect'
  get '/callback', to: 'calendar_api#callback', as: 'callback'
  get '/calendars', to: 'calendar_api#calendars', as: 'calendars'
  get '/events/:calendar_id', to: 'calendar_api#events', as: 'events', calendar_id: /[^\/]+/
  post '/events/:calendar_id', to: 'calendar_api#new_event', as: 'new_event', calendar_id: /[^\/]+/
  get '/new_interview/:id', to: 'calendar_api#new_interview', as: 'new_interview'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/position.rb
class Position < ApplicationRecord
    # Relation
    has_and_belongs_to_many :skills
    has_and_belongs_to_many :traits
    has_many :applicants

    # Validations
    validates :title, presence: true, length: { minimum: 5 }
    validates :description, presence: true, length: {minimum: 15}
    validates :title, uniqueness: { case_sensitive: false }
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  def index
    @positions = Position.all
  end

  def show
    @position = Position.find(params[:id])
    get_position_skills
    get_position_traits
  end

  def new
    @position = Position.new
  end

  def edit
    @position = Position.find(params[:id])
    get_position_skills
    get_position_traits
  end

  def create

    # Newly created positions are active by default.
    params[:position]["active"] = true

    # Saving new position
    @position = Position.new(position_params)
    if @position.save

      # Get array of skills and traits
      skills = listify_from_string(params[:skills])
      traits = listify_from_string(params[:traits])

      # Put skills in db and associate to position
      add_associations(Skill, skills, @position)

      # Put traits in db and associate to position
      add_associations(Trait, traits, @position)

      redirect_to @position
    else
      render 'new'
    end

  end

  def update
    @position = Position.find(params[:id])

    current_skills = get_position_skills
    current_traits = get_position_traits
    
    new_skills = listify_from_string(params[:skills])
    new_traits = listify_from_string(params[:traits])

    if @position.update(position_params)
      if current_skills != new_skills
        # Remove all skills from this position
        @position.skills.clear
        # Put skills in db and associate to position
        add_associations(Skill, new_skills, @position)
      end

      if current_traits != new_traits
        # Remove all traits from this position
        @position.traits.clear
        # Put traits in db and associate to position
        add_associations(Trait, new_traits, @position)
      end
      redirect_to @position
    else
      render 'edit'
    end
  
  end

  def destroy
    @position = Position.find(params[:id])
    @position.destroy

    redirect_to positions_path
  end

  
  private
    # Check that parameters contains only allowed values.
    def position_params
      params.require(:position).permit(:title, :description, :active)
    end

    def get_position_skills
      @skills = []
      for s in @position.skills do
        @skills.push(s.name)
      end
      return @skills
    end

    def get_position_traits
      @traits = []
      for t in @position.traits do
        @traits.push(t.name)
      end
      return @traits
    end
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/views/positions/edit.html.erb
<div class="container">
<h1>Edit position</h1>
 
<%= form_with(model: @position, local: true) do |form| %>
 
    <% if @position.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@position.errors.count, "error") %> prohibited
        this position from being saved:
      </h2>
      <ul>
        <% @position.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :active %><br>
    <%= form.check_box :active %>
  </p> 

  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= label_tag(:skills, "Skills") %>
    <%= text_field_tag(:skills, @skills.join(", ")) %>
  </p>

  <p>
    <%= label_tag(:traits, "Traits") %>
    <%= text_field_tag(:traits, @traits.join(", ")) %>
  </p>

  <p>
    <%= form.submit(class: 'btn btn-success') %>
  </p>
  
<% end %>
 <hr>
<%= link_to 'Back', position_path, class: 'btn btn-primary' %>
<%= link_to 'Destroy', position_path(@position),
              method: :delete,
              data: { confirm: 'Are you sure?' },
              class: 'btn btn-danger' %>
</div>

app/views/positions/index.html.erb
<div class="container">
    <h1>Position list</h1>
    <%= link_to 'New Position', new_position_path, class: 'btn btn-success' %> 
    <table class="table table-hover" style="margin-top: 20px">
    <thead class="thead-dark">
    <tr>
        <th>Title</th>
        <th>Aplicants</th>
    </tr>
    </thead>
    
    <% @positions.each do |position| %>
        <% if position.active %>
        <tr>
        <% else %>
        <tr class="table-warning">
        <%end %>
        <td><%= link_to position.title, position_path(position) %></td>
        <td><%= link_to position.applicants.length, "positions/#{position.id}/applicants" %></td>
        </tr>
    <% end %>
    </table>
</div>

app/views/positions/new.html.erb
<div class="container">
<h1>New Position</h1>

<%= form_with scope: :position, url: positions_path, local: true do |form| %>
  
  <% if @position.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@position.errors.count, "error") %> prohibited
        this position from being saved:
      </h2>
      <ul>
        <% @position.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
  
  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= label_tag(:skills, "Skills") %>
    <%= text_field_tag(:skills) %>
  </p>

  <p>
    <%= label_tag(:traits, "Traits") %>
    <%= text_field_tag(:traits) %>
  </p>
  
  <p>
    <%= form.submit(class: 'btn btn-success') %>
  </p>

<% end %>
<hr>
<%= link_to 'Back', positions_path, class: 'btn btn-primary'%>
</div>

app/views/positions/show.html.erb
<div class="container">

<h1>
    <%= @position.title %>
</h1>

<p>
  <strong>Active:</strong>
  <%= @position.active %>
</p>

<p>
  <strong>Description:</strong>
  <%= @position.description %>
</p>

<p>
  <strong>Skills:</strong>
  <%= @skills.join(", ") %>
</p>

<p>
  <strong>Traits:</strong>
  <%= @traits.join(", ") %>
</p>

<%= link_to 'Edit', edit_position_path(@position), class: 'btn btn-warning' %>
<%= link_to 'Positions', positions_path, class: 'btn btn-primary' %>
<%= link_to 'Create New Applicant', "/applicants/new/#{@position.id}", class: 'btn btn-success' %>
</div>