config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'positions#index'
  
  # Positions related routes
  resources :positions

  # Applicant related routes
  get '/applicants/new/:id', to: 'applicants#new'
  post '/applicants/create/:id', to: 'applicants#create'
  get '/applicants/:id', to: 'applicants#show', as: 'applicant'
  get '/applicants/:id/edit', to: 'applicants#edit'
  patch '/applicants/:id', to: 'applicants#update'
  get '/applicants', to: 'applicants#index'
  delete '/applicants/:id', to: 'applicants#destroy'
  get '/positions/:id/applicants', to: 'applicants#positions'
  get '/applicants/:id/recruiters', to: 'applicants#recruiters'
  post '/applicants/update_recruiter/:id', to: 'applicants#update_recruiter'
  post '/applicant_invite/:id', to: 'applicants#applicant_invite'

  # Positions related routes
  resources :recruiters

  # Google calendar routes
  get '/redirect', to: 'calendar_api#redirect', as: 'redirect'
  get '/callback', to: 'calendar_api#callback', as: 'callback'
  get '/calendars', to: 'calendar_api#calendars', as: 'calendars'
  get '/events/:calendar_id', to: 'calendar_api#events', as: 'events', calendar_id: /[^\/]+/
  post '/events/:calendar_id', to: 'calendar_api#new_event', as: 'new_event', calendar_id: /[^\/]+/
  get '/new_interview/:id', to: 'calendar_api#new_interview', as: 'new_interview'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/applicant.rb
class Applicant < ApplicationRecord
    has_and_belongs_to_many :skills
    belongs_to :position
    belongs_to :recruiter, optional: true
    has_many :trait_scores
    has_many :traits, through: :trait_scores

    def fullname
        return self.name + " " + self.surname
    end

end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController

    def index
        @applicants = Applicant.all
    end

    def show
        @applicant = Applicant.find_by(id: params[:id])
    end

    # Applicant is by default assigned to specific position
    def new
        position_id = params[:id]
        @position = Position.find(params[:id])
    end
    
    def edit
        @applicant = Applicant.find_by(id: params[:id])
        @position = Position.find_by(id: @applicant.position.id)
    end

    def create
        @position = Position.find_by(id: params[:id])

        # Retrieve status of skills and traits from form
        skills = params[:skills]
        traits = params[:traits]

        # If skills was not submitted make the hash anyway
        if !skills
            skills = {}
        end
        if !traits
            traits = {}
        end

        # Check if there is such position (for security)
        if @position
            # Hold parameters to submit to DB
            applicant_parameters = ActionController::Parameters.new({
                applicant: {
                    name: params[:name],
                    surname: params[:surname],
                    email: params[:user][:address],
                    position_id: @position.id
                }
            })

            @applicant = Applicant.new(applicant_params(applicant_parameters))
            if @applicant.save            
               
                # Add skills to applicant
                for s in skills.keys do
                    if skills[s] == "1"
                        skill = Skill.find_or_create_by(name: s)
                        @applicant.skills << skill
                    end
                end

                # Add traits to applicant
                for t in traits.keys do
                    trait = Trait.find_or_create_by(name: t)
                    TraitScore.create score: traits[t].to_i, applicant: @applicant, trait: trait
                end
                
                redirect_to "/applicants/#{@applicant[:id]}"
            else
                render "new"
            end     
        end
    end

    def update

        @applicant = Applicant.find_by(id: params[:id])
        new_skills = params[:skills]
        new_traits = params[:traits]

        # Delete current applicant skills
        @applicant.skills.clear
        # Add new skills
        for s in new_skills.keys do
            skill = Skill.find_or_create_by(name: s)
            @applicant.skills << skill
        end

        # Delete current applicant traits
        @applicant.traits.clear
        # Add traits to applicant
        for t in new_traits.keys do
            trait = Trait.find_or_create_by(name: t)
            TraitScore.create score: new_traits[t].to_i, applicant: @applicant, trait: trait
        end

        if @applicant.update(applicant_params(params))
            redirect_to "/applicants/#{@applicant[:id]}"
        else
            render 'edit'
        end
        
    end

    def destroy
        @applicant = Applicant.find(params[:id])
        @applicant.destroy
    
        redirect_to "/applicants"
    end

    # Show all applications for specific position
    def positions
        position_id = params[:id]
        @position = Position.find_by(id: position_id)
        @applicants = @position.applicants
        
        # Arrange applicant skills for easier use in view
        @skills = {}
        for applicant in @applicants do
            @skills[applicant[:id]] = []
            for skill in applicant.skills do
                @skills[applicant[:id]].push(skill.name)
            end
        end
    end

    # Logic for suggesting recruiters for applicants
    def recruiters
        applicant_id = params[:id]
        applicant = Applicant.find_by(id: applicant_id)
        recruiters = Recruiter.all

        # First, see if can establish match with skills
        applicants_skills = get_skills_list(applicant)
        if applicants_skills.length > 1

            # Make nice hash with recruiter skills
            recruiters_skills = {}
            for recruiter in recruiters do
                recruiters_skills[recruiter.id] = get_skills_list(recruiter)
            end

            # Determine applicant and recruiter skill intersection
            for recruiter in recruiters_skills.keys do
                recruiters_skills[recruiter] = recruiters_skills[recruiter] & applicants_skills
            end
            recruiters_skills = recruiters_skills.sort_by { |k, v| v.length }.reverse
            
            # No overlapping skills means no match
            if recruiters_skills[0][0] > 0

                best_id = recruiters_skills[0][0]
                best = Recruiter.find_by(id: best_id)
                @choice = {
                    id: best_id,
                    on: "skills",
                    name: best.name + " " + best.surname,
                    applicant_id: applicant_id
                }
            end
        end

        # If skills did not match, see who has most experience
        # by comparing number of applicants linked to recruiter
        if @choice == nil

            # Get the hash with applicant count for each recruiter
            recruiters_experience = {}
            for recruiter in recruiters do
                recruiters_experience[recruiter.id] = recruiter.applicants.length
            end
            recruiters_experience = recruiters_experience.sort_by { |k, v| v }.reverse
            
            # Chose highest if it has at least one applicant linked to it
            if recruiters_experience[0][1] > 0

                best_id = recruiters_experience[0][0]
                best = Recruiter.find_by(id: best_id)
                @choice = {
                    id: best_id,
                    on: "experience",
                    name: best.name + " " + best.surname,
                    applicant_id: applicant_id
                }
            end
        end

        # If boot previous logic did not return match,
        # choose recruiter randomly
        if @choice == nil
            offset = rand(Recruiter.count)
            recruiter = Recruiter.offset(offset).first
            @choice = {
                    id: recruiter.id,
                    on: "luck",
                    name: recruiter.name + " " + recruiter.surname,
                    applicant_id: applicant_id
                }
        end

        # Get all recruiter for option to chose
        @options = []
        for r in recruiters do
            @options.push([r.name + " " + r.surname, r.id])
        end

        # For Modal
        respond_to do |format|
            format.html
            format.js
        end

    end

    # Save recruiter for applicant
    def update_recruiter
        @applicant = Applicant.find_by(id: params[:id])
        recruiter = Recruiter.find_by(id: params[:chosen_recruiter])

        params = ActionController::Parameters.new({
                applicant: {
                    recruiter_id: recruiter.id
                }
            })
        @applicant.update(applicant_params(params))
        redirect_to "/applicants/#{@applicant[:id]}"

    end

    # When interview date and time is chosen send
    # send email invitations and save the date-time
    def applicant_invite
        require 'date'  # For DateTime.new
        
        # Create Date time value
        date = params[:applicant].values
        meeting_time = DateTime.new(date[0].to_i, date[1].to_i, date[2].to_i, date[3].to_i, date[4].to_i, 0)
        
        @applicant = Applicant.find_by(id: params[:id])
        recruiter = @applicant.recruiter
        
        # Save meeting time
        params = ActionController::Parameters.new({
                applicant: {
                    meeting: meeting_time
                }
            })
        @applicant.update(applicant_params(params))
        
        
        # Send emails
        UserMailer.with(applicant: @applicant, recruiter: recruiter, meeting_time: meeting_time).applicant_meeting_email.deliver_now
        UserMailer.with(applicant: @applicant, recruiter: recruiter, meeting_time: meeting_time).recruiter_meeting_email.deliver_now
        
        # Make calendar invitations.
        redirect_to new_interview_url(@applicant.id)

        #redirect_to "/applicants/#{@applicant[:id]}"
    end


    private
        # Check that parameters contains only allowed values.
        def applicant_params (params)
            params.require(:applicant).permit(:name, :surname, :email, :position_id, :recruiter_id, :meeting)
        end
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/views/applicants/_recruiters.html.erb
<div class="modal-header">
  <h4 class="modal-title" id="myModalLabel">Choose a recruiter</h4>
  <button type="button" class="close" data-dismiss="modal">x</button>
</div>
<div class="modal-body">
  <p>Suggested recruiter is</p>
  <h4><%= @choice[:name] %></h4>
  <p>Based on:<p>
  <h4><%= @choice[:on] %></h4>
  <p>You can chose another:</p>
  <%= form_with( url: "update_recruiter/#{@choice[:applicant_id]}", local: true) do %>
    <%= token_tag %> 
    <%= select_tag(:chosen_recruiter, options_for_select(@options, @choice[:id])) %>
    <%= submit_tag("Save") %>
  <% end %>
</div>
<div class="modal-footer">

</div>

app/views/applicants/edit.html.erb
<div class="container">
<h1>Edit applicant</h1>

<p>
  <strong>Position:</strong>
  <%= @applicant.position.title %>
</p>
<%= form_with(model: @applicant, local: true, url: "/applicants/#{@applicant.id}") do |form| %>

    <% if @applicant && @applicant.errors.any? %>
        <div id="error_explanation">
        <h2>
            <%= pluralize(@applicant.errors.count, "error") %> prohibited
            this applicant from being saved:
        </h2>
        <ul>
            <% @applicant.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>
        </div>
    <% end %>
    
    <p>
        <b><%= form.label :name %></b>
        <%= form.text_field :name %>
    </p>

    <p>
        <b><%= form.label :surname %></b>
        <%= form.text_field :surname %>
    </p>

    <p>
        <b><%= form.label :email %></b>
        <%= form.text_field :email %>
    </p>
    
    <%= fields_for :skills do |skill_form| %>
        <p><b>Skills:</b></p>
        <ul>
        <% for s in @position.skills do %>
            <li>
            <% if @applicant.skills.include? s %>
                yes
            <% end %>
            <%= check_box_tag "skills[#{s.name}]", 1, (@applicant.skills.include? s) %>
            <%= s.name %>
            </li>
        <% end %>
        </ul>
    <% end %>

    <%= fields_for :traits do |trait_form|%>
        <% n=0 %>
        <% traits={} %>
        <% for t in @applicant.traits do %>
            <% traits[t.name] = @applicant.trait_scores[n].score %>
            <% n+=1 %>
        <% end %>
        <p style="margin-bottom: 0"><b>Traits:</b></p>
        <p><small>(higher is better)</small></p>
        <ul>
        <% for t in @position.traits do %>
            <li>
            <select name="traits[<%= t.name %>]" id="trait_<%= t.name %>">
                <% for n in 1..5 do %>
                    <option value="<%= n %>"
                        <% if traits[t.name] == n %>
                            selected="selected"
                        <% end %>
                    ><%= n %></option>
                <% end %>
            </select>
            <%= t.name %>
            </li>
        <% end %>
        </ul>
    <% end %>


    <%= submit_tag("Save", {class: 'btn btn-success'}) %>


  <% end %>
<hr>
  <%= link_to 'Back', applicant_path, class: 'btn btn-primary' %>
  <%= link_to 'Destroy', applicant_path(@applicant),
                method: :delete,
                data: { confirm: 'Are you sure you want to destroy applicant by never answering to his/her resume?' },
                class: 'btn btn-danger' %>
</div>

app/views/applicants/index.html.erb
<div class="container">
    <h1>All Applicants</h1>
    <table class="table table-hover">
    <thead class="thead-dark">
    <tr>
        <th>Full name</th>
        <th>Position</th>
    </tr>
    </thead>
    
    <% @applicants.each do |applicant| %>
        <tr>
        <td><%= link_to applicant.fullname, applicant_path(applicant) %></td>
        <td><%= link_to applicant.position.title, position_path(applicant.position) %></td>
        </tr>
    <% end %>
    </table>
</div>

app/views/applicants/new.html.erb
<div class="container">

<h1>
  New applicant for <%= @position.title %>
</h1>
<%= form_with(url: "/applicants/create/#{@position.id}") do %>

    <% if @applicant && @applicant.errors.any? %>
        <div id="error_explanation">
        <h2>
            <%= pluralize(@applicant.errors.count, "error") %> prohibited
            this applicant from being saved:
        </h2>
        <ul>
            <% @applicant.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>
        </div>
    <% end %>

    <p>
        <b><%= label_tag(:name, "Name:") %></b>
        <%= text_field_tag(:name) %>
    </p>

    <p>
        <b><%= label_tag(:surname, "Surname:") %></b>
        <%= text_field_tag(:surname) %>
    </p>

    <p>
        <b><%= label_tag(:email, "Email:") %></b>
        <%= email_field(:user, :address) %>
    </p>
    
    <%= fields_for :skills do |skill_form| %>
        <p><b>Skills:</b></p>
        <ul>
        <% for s in @position.skills do %>
            <li>
            <%= skill_form.check_box s.name %>
            <%= s.name %>
            </li>
        <% end %>
        </ul>
    <% end %>

    <%= fields_for :traits do |trait_form|%>
        <p><b>Traits:</b></p>
        <p>(higher is better)</p>
        <ul>
        <% for t in @position.traits do %>
            <li>
            <select name="traits[<%= t.name %>]" id="trait_<%= t.name %>">
                <% for n in 1..5 do %>
                    <option value="<%= n %>"><%= n %></option>
                <% end %>
            </select>
            <%= t.name %>
            </li>
        <% end %>
        </ul>
    <% end %>


    <%= submit_tag("Create", class: 'btn btn-success') %>
    

  <% end %>
</div>

app/views/applicants/positions.html.erb
<div class="container">
    <h1>
    Appicants for
    <%= @position.title %>
    </h1>

    <table class="table table-hover">
    <thead class="thead-dark">
        <tr>
            <th>Full name</th>
            <th>Email</th>
            <th>Skills</th>
        </tr>
    </thead>
        
        <% @applicants.each do |applicant| %>
            <tr>
            <td><%= link_to applicant.fullname, "/applicants/#{applicant.id}" %></td>
            <td><%= applicant.email %></td>
            <td><%= @skills[applicant.id].join(", ") %></td>
            </tr>
        <% end %>
    </table>

<%= link_to 'Back', positions_path, class: 'btn btn-primary' %>
<%= link_to 'New', "/applicants/new/#{@position.id}", class: 'btn btn-success' %>
</div>

app/views/applicants/recruiters.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'recruiters') %>");
$("#modal-window").modal();

app/views/applicants/show.html.erb
<div class="container">
<h1>Applicant</h1>
<p>
    <strong>Position:</strong>
    <%= @applicant.position.title %>
</p>

<p>
    <strong>Name:</strong>
    <%= @applicant.name %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @applicant.surname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @applicant.email %>
</p>

<p>
    <strong>Recruiter:</strong>
    <% if @applicant.recruiter %>
        <%= link_to @applicant.recruiter.name + " " + @applicant.recruiter.surname, "/recruiters/#{@applicant.recruiter.id}" %>
    <% else %>
        Not selected
    <% end %>
</p>

<p>
    <strong>Skills:</strong>
</p>
<ul>
<% for s in @applicant.skills do %>
    <li><%= s.name %></li>
<% end %>
</ul>

<p>
    <strong>Traits:</strong>
</p>
<ul>
<% n = 0 %>
<% for t in @applicant.traits do %>
    <li>Score: <%= @applicant.trait_scores[n].score %>, Trait: <%= @applicant.traits[n].name %></li>
    <% n += 1 %>
<% end %>
</ul>

<p>
    <strong>Meeting time:</strong>
    <% if @applicant.meeting %>
        <%= @applicant.meeting %>
    <% else %>
        Not invited
    <% end %>
</p>
<% if @applicant.recruiter %>
<%= simple_form_for(@applicant, method: 'post', url: "/applicant_invite/#{@applicant.id}", html: { class: 'form-inline' }) do |f| %>
    <strong>
        <%= f.input :meeting, label: 'Invite applicant to interview:', as: :datetime%>
    </strong>
    <%= f.submit 'Invite', { class: 'btn btn-warning' } %>
<% end %>
<% else %>
<p>Before inviting applicant to meeting select recruiter</p>
<% end %>

<hr/>
<%= link_to 'Edit', "/applicants/#{@applicant.id}/edit", {class: 'btn btn-warning'} %>
<%= link_to 'Applicants', applicants_path, {class: 'btn btn-primary'} %>
<%= link_to 'Select recruiter', "/applicants/#{@applicant.id}/recruiters",  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'btn btn-success'}  %>
</div>

<div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content"></div>
  </div>
</div>