config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'positions#index'
  
  # Positions related routes
  resources :positions

  # Applicant related routes
  get '/applicants/new/:id', to: 'applicants#new'
  post '/applicants/create/:id', to: 'applicants#create'
  get '/applicants/:id', to: 'applicants#show', as: 'applicant'
  get '/applicants/:id/edit', to: 'applicants#edit'
  patch '/applicants/:id', to: 'applicants#update'
  get '/applicants', to: 'applicants#index'
  delete '/applicants/:id', to: 'applicants#destroy'
  get '/positions/:id/applicants', to: 'applicants#positions'
  get '/applicants/:id/recruiters', to: 'applicants#recruiters'
  post '/applicants/update_recruiter/:id', to: 'applicants#update_recruiter'
  post '/applicant_invite/:id', to: 'applicants#applicant_invite'

  # Positions related routes
  resources :recruiters

  # Google calendar routes
  get '/redirect', to: 'calendar_api#redirect', as: 'redirect'
  get '/callback', to: 'calendar_api#callback', as: 'callback'
  get '/calendars', to: 'calendar_api#calendars', as: 'calendars'
  get '/events/:calendar_id', to: 'calendar_api#events', as: 'events', calendar_id: /[^\/]+/
  post '/events/:calendar_id', to: 'calendar_api#new_event', as: 'new_event', calendar_id: /[^\/]+/
  get '/new_interview/:id', to: 'calendar_api#new_interview', as: 'new_interview'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/recruiter.rb
class Recruiter < ApplicationRecord
    has_and_belongs_to_many :skills
    has_many :applicants

    def fullname
        return self.name + " " + self.surname
    end
end

app/controllers/recruiters_controller.rb
class RecruitersController < ApplicationController

    def index
        @recruiters = Recruiter.all
    end

    def show
        @recruiter = Recruiter.find_by(id: params[:id])
    end
    
    def new
        @recruiter = Recruiter.new
    end

    def edit
        @recruiter = Recruiter.find_by(id: params[:id])
        @skills = get_skills_list(@recruiter)
    end

    def create

        # Saving new position
        @recruiter = Recruiter.new(recruiter_params)
        if @recruiter.save
            # Get array of skills
            skills = listify_from_string(params[:skills])
            # Put skills in db and associate to recruiter
            add_associations(Skill, skills, @recruiter)
            
            redirect_to @recruiter
        else
            render 'new'
        end
    end

    def update
        @recruiter = Recruiter.find_by(id: params[:id])

        current_skills = get_skills_list(@recruiter)
        new_skills = listify_from_string(params[:skills])

        if @recruiter.update(recruiter_params)
            if current_skills != new_skills
                # Remove all skills from this recruiter
                @recruiter.skills.clear
                # Put skills in db and associate to recruiter
                add_associations(Skill, new_skills, @recruiter)
            end
            redirect_to @recruiter
        else
            render 'edit'
        end
    end

    def destroy
        @recruiter = Recruiter.find(params[:id])
        @recruiter.destroy
    
        redirect_to recruiters_path
      end

    private
        # Check that parameters contains only allowed values.
        def recruiter_params
            params.require(:recruiter).permit(:name, :surname, :email)
        end

end

app/helpers/recruiters_helper.rb
module RecruitersHelper
end

app/views/recruiters/edit.html.erb
<div class="container">
<h1>Edit Recruiter</h1>

<%= form_with(model: @recruiter, local: true) do |form| %>
  
  <% if @recruiter.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@recruiter.errors.count, "error") %> prohibited
        this recruiter from being saved:
      </h2>
      <ul>
        <% @recruiter.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <b><%= form.label :name %></b>
    <%= form.text_field :name %>
  </p>
  
  <p>
    <b><%= form.label :surname %></b>
    <%= form.text_field :surname %>
  </p>

  <p>
    <b><%= form.label :email %></b>
    <%= form.text_field :email %>
  </p>

  <p>
    <b><%= label_tag(:skills, "Skills") %></b>
    <%= text_field_tag(:skills, @skills.join(", ")) %>
  </p>
  
  <p>
    <%= form.submit(class: 'btn btn-success') %>
  </p>

<% end %>
<hr>
<%= link_to 'Back', recruiters_path, class: 'btn btn-primary' %>
<%= link_to 'Delete', recruiter_path(@recruiter),
              method: :delete,
              data: { confirm: 'Are you sure?' },
              class: 'btn btn-danger' %>
</div>

app/views/recruiters/index.html.erb
<div class="container">
    <h1>Recruiter list</h1>
    <%= link_to 'New Recruiter', new_recruiter_path, class: 'btn btn-success' %> 
    <table class="table table-hover" style="margin-top: 20px">
    <thead class="thead-dark">
    <tr>
        <th>Full name</th>
        <th>Email</th>
    </tr>
    </thead>
    
    <% @recruiters.each do |recruiter| %>
        <tr>
        <td><%= link_to recruiter.fullname, recruiter_path(recruiter) %></td>
        <td><%= recruiter.email %></td>
        </tr>
    <% end %>
    </table>
</div>

app/views/recruiters/new.html.erb
<div class="container">
<h1>New Recruiter</h1>

<%= form_with scope: :recruiter, url: recruiters_path, local: true do |form| %>
  
  <% if @recruiter.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@recruiter.errors.count, "error") %> prohibited
        this recruiter from being saved:
      </h2>
      <ul>
        <% @recruiter.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <b><%= form.label :name %></b>
    <%= form.text_field :name %>
  </p>
  
  <p>
    <b><%= form.label :surname %></b>
    <%= form.text_field :surname %>
  </p>

  <p>
    <b><%= form.label :email %></b>
    <%= form.text_field :email %>
  </p>

  <p>
    <b><%= label_tag(:skills, "Skills") %></b>
    <%= text_field_tag(:skills) %>
  </p>
  
  <p>
    <%= form.submit(class: 'btn btn-success') %>
  </p>

<% end %>
<hr>
<%= link_to 'Back', recruiters_path, class: 'btn btn-primary' %>
</div>

app/views/recruiters/show.html.erb
<div class="container">
<h1>Recruiter</h1>
<p>
    <strong>Name:</strong>
    <%= @recruiter.name %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @recruiter.surname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @recruiter.email %>
</p>

<p>
    <strong>Skills:</strong>
</p>
<ul>
<% for s in @recruiter.skills do %>
    <li><%= s.name %></li>
<% end %>
</ul>


<%= link_to 'Edit', edit_recruiter_path(@recruiter), {class: 'btn btn-warning'} %>
<%= link_to 'Recruiters', recruiters_path, {class: 'btn btn-primary'} %>
</div>