config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'positions#index'
  
  # Positions related routes
  resources :positions

  # Applicant related routes
  get '/applicants/new/:id', to: 'applicants#new'
  post '/applicants/create/:id', to: 'applicants#create'
  get '/applicants/:id', to: 'applicants#show', as: 'applicant'
  get '/applicants/:id/edit', to: 'applicants#edit'
  patch '/applicants/:id', to: 'applicants#update'
  get '/applicants', to: 'applicants#index'
  delete '/applicants/:id', to: 'applicants#destroy'
  get '/positions/:id/applicants', to: 'applicants#positions'
  get '/applicants/:id/recruiters', to: 'applicants#recruiters'
  post '/applicants/update_recruiter/:id', to: 'applicants#update_recruiter'
  post '/applicant_invite/:id', to: 'applicants#applicant_invite'

  # Positions related routes
  resources :recruiters

  # Google calendar routes
  get '/redirect', to: 'calendar_api#redirect', as: 'redirect'
  get '/callback', to: 'calendar_api#callback', as: 'callback'
  get '/calendars', to: 'calendar_api#calendars', as: 'calendars'
  get '/events/:calendar_id', to: 'calendar_api#events', as: 'events', calendar_id: /[^\/]+/
  post '/events/:calendar_id', to: 'calendar_api#new_event', as: 'new_event', calendar_id: /[^\/]+/
  get '/new_interview/:id', to: 'calendar_api#new_interview', as: 'new_interview'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="/">RecruitR</a>
    <a class="btn btn-outline-primary" href=<%= positions_path %> role="button">
    Positions
    </a>
      <a class="btn btn-outline-success" href=<%= applicants_path %> role="button">
      Applicants
      </a>
    <a class="btn btn-outline-warning" href=<%= recruiters_path %> role="button">
    Recruiters
    </a>
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecruitR</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= render "layouts/alerts" %>
    <%= yield %>
  </body>
</html>